### ISSUE TITLE
Not an issue, just an idea.

### ISSUE THREAD

**Issue by GabubuAvailable** [Greeg0/BounceWii#1]
The new idea is to add a feature that you can turn off the Wii, directly from the BounceWii app, using the Power Button from Wii Remote. This feature would be helpful when you want to turn off the Wii directly from the BounceWii app.

**Comment by Greeg0** [comment]
This. Yeah I plan to add this too, and I will try to make it exactly the same as shutting off other wii programs, with your preferred shut off mode IE standby or completely off. Thank you.
